### ISSUE TITLE
[enhancement] Review of Docker build process

### ISSUE THREAD

**Issue by crazy-max** [karalabe/xgo#130]
Hi @karalabe,

I have [forked your repo](https://github.com/crazy-max/xgo) and made some changes to push images and tags to an unique docker repository to make things more consistent for users.

I use [travis](https://travis-ci.org/crazy-max/xgo/builds/429769403) and his [matrix expansion](https://docs.travis-ci.com/user/build-stages/matrix-expansion/) to build the images instead of using automated builds of Docker Hub (see my [.travis.yml](https://github.com/crazy-max/xgo/blob/master/.travis.yml)).

If you launch a simple travis build, only the base image will be built. If you want to build X images you have to trigger a custom build using this content :

```yml
matrix:
  include:
    - name: "xgo 1.10.0"
      env:
        - DOCKERFILE=./docker/go-1.10.0/Dockerfile
        - BUILDPATH=./docker/go-1.10.0
        - VERSION=1.10.0
        - NOT_PUSH_LATEST=true
    - name: "xgo 1.10.1"
      env:
        - DOCKERFILE=./docker/go-1.10.1/Dockerfile
        - BUILDPATH=./docker/go-1.10.1
        - VERSION=1.10.1
        - NOT_PUSH_LATEST=true

matrix:
  include:
    - name: "xgo 1.10.x"
      env:
        - DOCKERFILE=./docker/go-1.10.x/Dockerfile
        - BUILDPATH=./docker/go-1.10.x
        - VERSION=1.10.x
        - NOT_PUSH_LATEST=true
```
> example with Go 1.10 images

![image](https://user-images.githubusercontent.com/1951866/45653046-d3900980-bad6-11e8-9406-590c6bd5fa77.png)

![image](https://user-images.githubusercontent.com/1951866/45653062-e99dca00-bad6-11e8-9ede-32dee72c3834.png)

Images and tags are pushed to an unique repository : https://hub.docker.com/r/crazymax/xgo/tags/
I think it would be more consistent if we did the same here.

We can improve more things by using a templating Dockerfile for all images and also launch your testsuite in travis.

What do you think ? Are you interested ?
